// <auto-generated />
using System;
using CrudTest.Infrastructure.Presistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudTest.Infrastructure.Presistance.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrudTest.Core.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BankAccountNumber")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PhoneNumber")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff336907-0499-11d1-0d89-6e2c525e39e5"),
                            BankAccountNumber = 1212121212121212m,
                            DateOfBirth = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ipdotsetaf.work@gmail.com",
                            FirstName = "Ali",
                            LastName = "Nazari",
                            PhoneNumber = 989387016860m
                        },
                        new
                        {
                            Id = new Guid("5c740a82-5dab-dd83-8452-e4299aaad12f"),
                            BankAccountNumber = 1212121212121212m,
                            DateOfBirth = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ipdotsetaf@gmail.com",
                            FirstName = "Mahdi",
                            LastName = "Nazari",
                            PhoneNumber = 989387016860m
                        },
                        new
                        {
                            Id = new Guid("b2c3a9ba-f1a9-2627-dce1-c0101ddfff08"),
                            BankAccountNumber = 1212121212121212m,
                            DateOfBirth = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testt@gmail.com",
                            FirstName = "Saeed",
                            LastName = "Rezaii",
                            PhoneNumber = 19387016860m
                        },
                        new
                        {
                            Id = new Guid("3dde6799-7063-d42e-ba04-85ff4e664534"),
                            BankAccountNumber = 1212121212121212m,
                            DateOfBirth = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@gmail.com",
                            FirstName = "Hooshang",
                            LastName = "Motahari",
                            PhoneNumber = 989387016860m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
